services:
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes: 
      - ./api/data:/data
    networks:
      - my-network
  api:
    image: loaymoh1170067/minlylite-api:latest
    restart: on-failure
    container_name: api
    ports:
      - '8000:8000'
    depends_on:
      - redis
    networks:
      - my-network
    env_file:
      - .env_api
    volumes:
      - ./api/data:/usr/src/app/data
      - ./api/logs:/usr/src/app/logs
      - ./api/src/storage/public:/usr/src/app/src/storage/public
  web:
    image: loaymoh1170067/minlylite-web:latest
    restart: on-failure
    container_name: web
    ports:
      - '3000:3000'
    env_file:
      - .env_web
    networks:
      - my-network
    # volumes:
    #   - ./web/:/app
    #   - /app/node_modules
    depends_on:
      - api
  nginx:
    build: ./nginx
    restart: on-failure
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - api
      - web
networks:
  my-network:
    driver: bridge