name: Build Docker Images

on:
  push:
    paths:
      - 'api/**'
      - 'web/**'
#  pull_request:
#    paths:
#      - 'api/**'
#      - 'web/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Determine changed files
        id: changes
        run: |
          echo "GITHUB_SHA: ${{ github.sha }}"
          echo "GITHUB_BASE_REF: ${{ github.event.pull_request.base.sha }}"
          api_changes=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^api/')
          web_changes=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^web/')
          if [ -n "$api_changes" ]; then
            echo "api_changed=true" >> $GITHUB_ENV
          else
            echo "api_changed=false" >> $GITHUB_ENV
          fi
          if [ -n "$web_changes" ]; then
            echo "web_changed=true" >> $GITHUB_ENV
          else
            echo "web_changed=false" >> $GITHUB_ENV
          fi
          echo "API changes: $api_changes"
          echo "Web changes: $web_changes"
          
      - name: Build API Docker image
        if: env.api_changed == 'true'
        run: |
          docker build -t minlylite/api:latest ./api
          docker push minlylite/api:latest

      - name: Build Web Docker image
        if: env.web_changed == 'true'
        run: |
          docker build -t minlylite/web:latest ./web
          docker push minlylite/web:latest
