name: Build Docker Images

on:
  push:
    branches:
      - main
    # paths:
    #   - "api/**"
    #   - "web/**"
#  pull_request:
#    paths:
#      - 'api/**'
#      - 'web/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      #      - name: Determine changed files
      #        id: changes
      #        run: |
      #          echo "api_changed=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^api/' && echo true || echo false)" >> $GITHUB_ENV
      #          echo "web_changed=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^web/' && echo true || echo false)" >> $GITHUB_ENV
      - name: Build API Docker image
        run: |
          echo "Building Api Docker image..."
          docker build --no-cache  -t loaymoh1170067/minlylite-api:latest ./api
          docker push loaymoh1170067/minlylite-api:latest

      - name: Build Web Docker image
        run: |
          echo "Building Web Docker image..."
          cd web/
          pwd
          docker build --no-cache  -t loaymoh1170067/minlylite-web:latest -f Dockerfile.dev .
          docker push loaymoh1170067/minlylite-web:latest
